build: racecondition producerconsumer

racecondition: racecondition.c
	gcc racecondition.c -o racecondition -pthread

producerconsumer:
	gcc producerconsumer.c -o producerconsumer -pthread

clean:
	rm racecondition producerconsumer
